profiles:
    bh22-win01:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9234
            selfSignedCert: false
            indices: win-111-winlogbeat-bh22-20220727
            options:
                dialects:
                  - beats
        config:
            auth:
                username: elastic
                password: <ES_PWD>
    bh22-win02:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9234
            selfSignedCert: false
            indices: win-111-winlogbeat-test-20220726
            options:
                dialects:
                  - beats
        config:
            auth:
                username: elastic
                password: <ES_PWD>
    bh22-linux:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9234
            selfSignedCert: false
            indices: linux-91-sysflow-test-20220725
            options:
                dialects:
                  - beats
        config:
            auth:
                username: elastic
                password: <ES_PWD>
